core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('', include('accounts.urls', namespace='accounts')),
    path('', include('uavs.urls', namespace='brand_api')),

]

# media urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uavs/urls.py
from django.urls import path, include
from .views import brand_form, brand_list, category_form, category_list, uav_form, uav_list, reservation_form, \
    reservation_list, account_reservation_list

app_name = "uavs"

urlpatterns = [
    path('api/', include('uavs.api.urls'), name='brand_api'),
    path('dashboard/brand/create/', brand_form, name='brand_form'),
    path('dashboard/brand/list/', brand_list, name='brand_list'),

    path('dashboard/category/create/', category_form, name='category_form'),
    path('dashboard/category/list/', category_list, name='category_list'),

    path('dashboard/uav/create/', uav_form, name='uav_form'),
    path('dashboard/uav/list/', uav_list, name='uav_list'),

    path('reservation/create/', reservation_form, name='reservation_form'),
    path('dashboard/reservation/list/', reservation_list, name='reservation_list'),

    path('accounts/reservation/list/', account_reservation_list, name='account_reservation_list'),
]

templates/dashboard/brand/form.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block body %}
    <form id="brandForm" class="space-y-4">
        <div>
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="name" name="name"
                   class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                   required>
        </div>
        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Kaydet
        </button>
    </form>
{% endblock %}

{% block extrascripts %}
    {{ block.super }}
    <script src="{% static 'js/dashboard/brand-form.js' %}"></script>
{% endblock %}

templates/dashboard/brand/list.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
{% endblock %}

{% block body %}
    <a type="button" href="{% url 'uavs:brand_form' %}">Create Brand</a>
    <table id="brandTable" class="display" style="width:100%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Slug</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Actions</th>
            <th></th>
        </tr>
        </thead>
    </table>
{% endblock %}

{% block extrascripts %}
    {{ block.super }}
    <script src="{% static 'js/dashboard/brand-list.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#brandTable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "/api/brand/",
                    "type": "GET"
                },
                "columns": [
                    {"data": "id"},
                    {"data": "name"},
                    {"data": "slug"},
                    {"data": "created_at"},
                    {"data": "updated_at"},
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            return '<button type="button" onclick="deleteBrand('+ row.id +')">Delete</button>';
                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            return '<a href="/api/brand/' + row.id + '/">Update</a>';
                        }
                    },
                ],

            });
        });
        
        function deleteBrand(id) {
            fetch('/api/brand/' + id + '/', {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                }
            }).then(response => {
                if (response.ok) {
                    alert('Brand deleted successfully');
                    $('#brandTable').DataTable().ajax.reload();
                } else {
                    alert('An error occurred');
                }
            });
        }
    </script>
{% endblock %}